### ISSUE TITLE
potentially invalid user: a non VMessAEAD connection is received.

### ISSUE THREAD

**Issue by lusins** [pitech007/v2ray#3]
v2ray服务器服务端总报错,说要更新客户端,但是客户端已经是最新的了,请帮忙解决一下哦,怎么解决这个问题哦?谢谢
 
 [Warning] github.com/v2fly/v2ray-core/v4/proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now.

**Comment by pitech007** [comment]
运行v2ray脚本，更新下服务端，然后下载3.29及以前的win客户端就好了

**Comment by lusins** [comment]
好的,谢谢
另外ios端的小火箭和mac 端的v2rayX要下载多少版本以前的客户端哦?我主要用这两个端~

**Comment by muzeshui** [comment]
[Warning] proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.

同样问题 但我的客户端是linux centos7 的 ，求解！！！
