### ISSUE TITLE
你好，我在输入acme.sh --register-account -m 12345@qq.com --server zerossl出现了问题

### ISSUE THREAD

**Issue by rw1995** [pitech007/v2ray#5]
`
[Thu Jul 29 16:03:07 UTC 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 51
[Thu Jul 29 16:03:09 UTC 2021] Can not init api for: https://acme.zerossl.com/v2/DV90.
[Thu Jul 29 16:03:09 UTC 2021] Sleep 10 and retry.
[Thu Jul 29 16:03:38 UTC 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 51
[Thu Jul 29 16:03:40 UTC 2021] Can not init api for: https://acme.zerossl.com/v2/DV90.
[Thu Jul 29 16:03:40 UTC 2021] Sleep 10 and retry.

`

当输入上面的命令行后，他就不段的重复报下面的循环，等了几分钟，依然是这个

**Comment by pitech007** [comment]
试了完全没问题，邮箱改个冷门或你自己的邮箱，别用12345这种可能很多人用过的邮箱，域名可以换新二级域名测试，同个域名在一段时间内只能申请限定次数

**Comment by rw1995** [comment]
[root@vultr ~]# acme.sh  --issue  -d b.wdfsdsgdfnsdhhrtjtgdgsd.xyz --standalone
[Fri Jul 30 01:34:14 UTC 2021] Using CA: https://acme.zerossl.com/v2/DV90
[Fri Jul 30 01:34:14 UTC 2021] Standalone mode.
[Fri Jul 30 01:34:14 UTC 2021] Single domain='b.wdfsdsgdfnsdhhrtjtgdgsd.xyz'
[Fri Jul 30 01:34:14 UTC 2021] Getting domain auth token for each domain
[Fri Jul 30 01:34:15 UTC 2021] Getting webroot for domain='b.wdfsdsgdfnsdhhrtjtgdgsd.xyz'
[Fri Jul 30 01:34:16 UTC 2021] Verifying: b.wdfsdsgdfnsdhhrtjtgdgsd.xyz
[Fri Jul 30 01:34:16 UTC 2021] Standalone mode server
[Fri Jul 30 01:34:17 UTC 2021] Processing, The CA is processing your order, please just wait. (1/30)
[Fri Jul 30 01:34:19 UTC 2021] Processing, The CA is processing your order, please just wait. (2/30)
[Fri Jul 30 01:34:22 UTC 2021] Processing, The CA is processing your order, please just wait. (3/30)


@pitech007  你好，上面那个=-=通过了，下面又一直这样，进行30轮之后，出现下列问题
[Fri Jul 30 01:35:29 UTC 2021] b.wdfsdsgdfnsdhhrtjtgdgsd.xyz:Timeout
[Fri Jul 30 01:35:29 UTC 2021] Please add '--debug' or '--log' to check more details.
[Fri Jul 30 01:35:29 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

请问如何解决

**Comment by rw1995** [comment]
已解决，需要开放防火墙端口
[网址参考](https://blog.csdn.net/shiyong1949/article/details/81196635)
